var typed = new Typed(".autoType", {
    strings: ["I'm Olyad Negero", "Front-End Web developer"],
    typeSpeed: 150,
    backSpeed: 150,
    loop: true,
    // loopCount: Infinity,
    // showCursor: true,
    // cursorChar: "|",
    // smartBackspace: true,
    // backDelay: 1500,
    // startDelay: 1000,
    // shuffle: true,
    // fadeOut: true,
    // fadeOutDelay: 500,
    // attr: null,
    // bindInputFocusEvents: true,
    // preStringTyped: function () {},
    // onStringTyped: function () {},
    // resetCallback: function () {},
    // shuffleDelay: 0,
    // shufflePeriod: 0,
    // contentType: 'html',
    // callback: function () {},
    // errorCallback: function () {}
})